# Generated by Django 5.2.5 on 2025-08-12 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("id_ride", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en-route", "En Route"),
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                        ],
                        default="en-route",
                        max_length=20,
                    ),
                ),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("dropoff_latitude", models.FloatField()),
                ("dropoff_longitude", models.FloatField()),
                ("pickup_time", models.DateTimeField()),
                (
                    "id_driver",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_driver",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides_as_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_rider",
                    models.ForeignKey(
                        db_column="id_rider",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides_as_rider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ride",
            },
        ),
    ]
