# Generated by Django 5.2.5 on 2025-08-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ride"),
    ]

    operations = [
        migrations.CreateModel(
            name="RideEvent",
            fields=[
                ("id_ride_event", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_ride",
                    models.ForeignKey(
                        db_column="id_ride",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.ride",
                    ),
                ),
            ],
            options={
                "db_table": "ride_event",
                "ordering": ["-created_at"],
            },
        ),
    ]
