# Generated by Django 5.2.5 on 2025-08-13 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rideevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rideevent",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
